// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

export class CreateRequest {
    /**
     * Creates a new CreateRequest instance.
     * @param {Partial<CreateRequest>} [$$source = {}] - The source object to create the CreateRequest.
     */
    constructor($$source = {}) {
        if (!("tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CreateRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateRequest(/** @type {Partial<CreateRequest>} */($$parsedSource));
    }
}

export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("input" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}
