// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CreateRequest {
    "tool": string;
    "title": string;
    "input": string;
    "output": string;
}

export interface Entry {
    "id": string;
    "tool": string;
    "title": string;
    "input": string;
    "output": string;
    "createdAt": string;
}
