// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";

export function Clear(tool: string): $CancellablePromise<void> {
    return $Call.ByID(2353432274, tool);
}

export function Create(req: history$0.CreateRequest): $CancellablePromise<history$0.Entry> {
    return $Call.ByID(508434189, req);
}

export function DataPath(): $CancellablePromise<string> {
    return $Call.ByID(3121878086);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(3921506394, id);
}

export function List(tool: string, limit: number): $CancellablePromise<history$0.Entry[] | null> {
    return $Call.ByID(671552305, tool, limit);
}
