// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";

/**
 * @param {string} tool
 * @returns {$CancellablePromise<void>}
 */
export function Clear(tool) {
    return $Call.ByID(2353432274, tool);
}

/**
 * @param {history$0.CreateRequest} req
 * @returns {$CancellablePromise<history$0.Entry>}
 */
export function Create(req) {
    return $Call.ByID(508434189, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function DataPath() {
    return $Call.ByID(3121878086);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(3921506394, id);
}

/**
 * @param {string} tool
 * @param {number} limit
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function List(tool, limit) {
    return $Call.ByID(671552305, tool, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} tool
 * @param {string} query
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function Search(tool, query, limit, offset) {
    return $Call.ByID(1691045273, tool, query, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = history$0.Entry.createFrom;
const $$createType1 = $Create.Array($$createType0);
