// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as HistoryService from "./historyservice.js";
import * as WindowService from "./windowservice.js";
export {
    HistoryService,
    WindowService
};
